export interface BookBuyer {
    nameOnCard: string,
    cardNum: string,
    cvv: string,
    exp: string,
    billingName: string,
    address: string,
    city: string,
    state: string,
    zipcode: string,
    phone: string,
    choice: string,
    isbn: String,
    title: String,
    author: String,
    price: Number,
    quantity: Number,
    location: String,
    creator: string,
}